package it.palsoftware.pastiera

/**
 * The main screen's groups (Keyboards & layouts, Typing, Look & sound, Apps) and the
 * screens that only exist since the settings were grouped by task. Their rows use
 * the same stable IDs.
 */
internal fun layoutSettingEntries(): List<SettingEntry> = listOf(
    SettingEntry(SettingLinkIds.MAIN_KEYBOARDS_LAYOUTS, R.string.settings_keyboards_layouts_title,
        summaryRes = R.string.settings_keyboards_layouts_description,
        route = SettingRoute(SettingsDestination.KeyboardsLayouts)),
    SettingEntry(SettingLinkIds.MAIN_TYPING, R.string.settings_typing_title,
        summaryRes = R.string.settings_typing_description,
        route = SettingRoute(SettingsDestination.Typing)),
    SettingEntry(SettingLinkIds.MAIN_EDITING_KEYS, R.string.settings_editing_keys_title,
        summaryRes = R.string.settings_editing_keys_description,
        route = SettingRoute(SettingsDestination.EditingKeys)),
    SettingEntry(SettingLinkIds.MAIN_LOOK_SOUND, R.string.settings_look_sound_title,
        summaryRes = R.string.settings_look_sound_description,
        route = SettingRoute(SettingsDestination.LookSound)),
    SettingEntry(SettingLinkIds.MAIN_APPS, R.string.settings_apps_title,
        summaryRes = R.string.settings_apps_description,
        route = SettingRoute(SettingsDestination.Apps)),
    SettingEntry(SettingLinkIds.MAIN_APP_SHORTCUTS, R.string.app_shortcuts_title,
        summaryRes = R.string.app_shortcuts_description,
        route = SettingRoute(SettingsDestination.AppShortcuts)),
    SettingEntry(SettingLinkIds.APP_SHORTCUTS_ENABLED, R.string.app_shortcuts_enabled_title,
        summaryRes = R.string.app_shortcuts_enabled_description,
        route = SettingRoute(SettingsDestination.AppShortcuts)),
    SettingEntry(SettingLinkIds.APP_SHORTCUTS_SUGGESTIONS, R.string.app_shortcuts_suggestions_title,
        summaryRes = R.string.app_shortcuts_suggestions_description,
        route = SettingRoute(SettingsDestination.AppShortcuts)),
    SettingEntry(SettingLinkIds.MODIFIERS_SMART_ALT_OFF, R.string.smart_alt_off_title,
        summaryRes = R.string.smart_alt_off_description,
        route = SettingRoute(SettingsDestination.Modifiers)),
    SettingEntry(SettingLinkIds.MODIFIERS_SMART_CTRL_OFF, R.string.smart_ctrl_off_title,
        summaryRes = R.string.smart_ctrl_off_description,
        route = SettingRoute(SettingsDestination.Modifiers)),
    SettingEntry(SettingLinkIds.DEVELOPER_OPTIONS_ENABLED, R.string.developer_options_title,
        summaryRes = R.string.developer_options_description,
        route = SettingRoute(SettingsDestination.Advanced)),
    SettingEntry(SettingLinkIds.MAIN_DEVELOPER, R.string.developer_options_title,
        summaryRes = R.string.developer_options_row_description,
        route = SettingRoute(SettingsDestination.Developer),
        availabilityCheck = { SettingsManager.getDeveloperOptionsEnabled(it) },
        unavailableFallbackId = SettingLinkIds.DEVELOPER_OPTIONS_ENABLED),
    SettingEntry(SettingLinkIds.MAIN_EXACT_TYPING, R.string.exact_typing_title,
        summaryRes = R.string.exact_typing_description,
        route = SettingRoute(SettingsDestination.ExactTyping)),
    SettingEntry(SettingLinkIds.EXACT_TYPING_NO_SUGGESTION_FIELDS, R.string.exact_typing_no_suggestions_title,
        summaryRes = R.string.exact_typing_no_suggestions_description,
        route = SettingRoute(SettingsDestination.ExactTyping)),
    SettingEntry(SettingLinkIds.MAIN_TERMINAL_MODE, R.string.terminal_mode_title,
        summaryRes = R.string.terminal_mode_description,
        route = SettingRoute(SettingsDestination.TerminalMode)),
    SettingEntry(SettingLinkIds.TERMINAL_MODE_ENABLED, R.string.terminal_mode_enabled_title,
        summaryRes = R.string.terminal_mode_enabled_description,
        route = SettingRoute(SettingsDestination.TerminalMode)),
    SettingEntry(SettingLinkIds.PRIVACY_INCOGNITO_ALWAYS, R.string.incognito_always_title,
        summaryRes = R.string.incognito_always_description,
        route = SettingRoute(SettingsDestination.Advanced)),
    SettingEntry(SettingLinkIds.PRIVACY_INCOGNITO_FOLLOW_APPS, R.string.incognito_follow_apps_title,
        summaryRes = R.string.incognito_follow_apps_description,
        route = SettingRoute(SettingsDestination.Advanced),
        availabilityCheck = { !SettingsManager.getIncognitoAlways(it) },
        unavailableFallbackId = SettingLinkIds.PRIVACY_INCOGNITO_ALWAYS),
    SettingEntry(SettingLinkIds.AUTO_CORRECTION_SUGGESTIONS_BOLD, R.string.suggestions_bold_title,
        summaryRes = R.string.suggestions_bold_description,
        route = SettingRoute(SettingsDestination.AutoCorrection)),
    SettingEntry(SettingLinkIds.AUTO_CORRECTION_EMOJI_SUGGESTIONS, R.string.emoji_suggestions_title,
        summaryRes = R.string.emoji_suggestions_description,
        route = SettingRoute(SettingsDestination.AutoCorrection)),
    SettingEntry(SettingLinkIds.TERMINAL_MODE_HIDE_KEYBOARD, R.string.terminal_mode_hide_keyboard_title,
        summaryRes = R.string.terminal_mode_hide_keyboard_description,
        route = SettingRoute(SettingsDestination.TerminalMode),
        availabilityCheck = { SettingsManager.getTerminalModeEnabled(it) },
        unavailableFallbackId = SettingLinkIds.TERMINAL_MODE_ENABLED),
    SettingEntry(SettingLinkIds.TERMINAL_MODE_EMOJI_KEY, R.string.terminal_mode_emoji_key_title,
        summaryRes = R.string.terminal_mode_emoji_key_description,
        route = SettingRoute(SettingsDestination.TerminalMode),
        availabilityCheck = { SettingsManager.getTerminalModeEnabled(it) },
        unavailableFallbackId = SettingLinkIds.TERMINAL_MODE_ENABLED),
    SettingEntry(SettingLinkIds.DEFAULT_CONFIG, R.string.default_config_title,
        summaryRes = R.string.default_config_description,
        route = SettingRoute(SettingsDestination.Advanced)),
    SettingEntry(SettingLinkIds.RECOMMENDED_SETTINGS, R.string.recommended_settings_title,
        summaryRes = R.string.recommended_settings_description,
        route = SettingRoute(SettingsDestination.Advanced)),
    SettingEntry(SettingLinkIds.MAIN_EMOJI_PROFILES, R.string.emoji_profiles_title,
        summaryRes = R.string.emoji_profiles_description,
        route = SettingRoute(SettingsDestination.EmojiProfiles)),
    SettingEntry(SettingLinkIds.EMOJI_PROFILES_SWITCH_BY_APP, R.string.emoji_profiles_switch_by_app_title,
        summaryRes = R.string.emoji_profiles_switch_by_app_description,
        route = SettingRoute(SettingsDestination.EmojiProfiles)),
    SettingEntry(SettingLinkIds.EMOJI_PROFILES_SAVE_CURRENT, R.string.emoji_profiles_save_current_title,
        summaryRes = R.string.emoji_profiles_save_current_description,
        route = SettingRoute(SettingsDestination.EmojiProfiles)),
    SettingEntry(SettingLinkIds.MAIN_LED_COLORS, R.string.led_colors_title,
        summaryRes = R.string.led_colors_description,
        route = SettingRoute(SettingsDestination.LedColors)),
    SettingEntry(SettingLinkIds.LED_INDIVIDUAL_COLORS, R.string.led_colors_individual_title,
        summaryRes = R.string.led_colors_individual_off,
        route = SettingRoute(SettingsDestination.LedColors)),
    SettingEntry(SettingLinkIds.LED_LOCKED_ANIMATION, R.string.led_locked_animation_title,
        summaryRes = R.string.led_locked_animation_description,
        route = SettingRoute(SettingsDestination.LedColors)),
    SettingEntry("led_colors.shift", R.string.led_colors_shift, route = SettingRoute(SettingsDestination.LedColors),
        availabilityCheck = { SettingsManager.getLedIndividualColorsEnabled(it) }, unavailableFallbackId = SettingLinkIds.LED_INDIVIDUAL_COLORS),
    SettingEntry("led_colors.ctrl", R.string.led_colors_ctrl, route = SettingRoute(SettingsDestination.LedColors),
        availabilityCheck = { SettingsManager.getLedIndividualColorsEnabled(it) }, unavailableFallbackId = SettingLinkIds.LED_INDIVIDUAL_COLORS),
    SettingEntry("led_colors.alt", R.string.led_colors_alt, route = SettingRoute(SettingsDestination.LedColors),
        availabilityCheck = { SettingsManager.getLedIndividualColorsEnabled(it) }, unavailableFallbackId = SettingLinkIds.LED_INDIVIDUAL_COLORS),
    SettingEntry("led_colors.sym", R.string.led_colors_sym, route = SettingRoute(SettingsDestination.LedColors),
        availabilityCheck = { SettingsManager.getLedIndividualColorsEnabled(it) }, unavailableFallbackId = SettingLinkIds.LED_INDIVIDUAL_COLORS),
    SettingEntry(SettingLinkIds.AUTO_CORRECTION_INLINE_AUTOFILL, R.string.inline_autofill_title,
        summaryRes = R.string.inline_autofill_description,
        route = SettingRoute(SettingsDestination.AutoCorrection),
        availabilityCheck = { android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.R }),
    SettingEntry(SettingLinkIds.AUTO_CORRECTION_SPELL_CHECKER, R.string.spell_checker_title,
        summaryRes = R.string.spell_checker_description,
        route = SettingRoute(SettingsDestination.AutoCorrection)),
    SettingEntry("hardware.alt_editor.in_use", R.string.alt_key_editor_in_use_title,
        summaryRes = R.string.alt_key_editor_use_description,
        route = SettingRoute(SettingsDestination.DeviceSymLayerEditor)),
    SettingEntry("hardware.alt_editor.blank", R.string.alt_key_editor_blank_profile_title,
        summaryRes = R.string.alt_key_editor_blank_profile_description,
        route = SettingRoute(SettingsDestination.DeviceSymLayerEditor)),
    SettingEntry("hardware.alt_editor.clone", R.string.alt_key_editor_clone_profile_title,
        summaryRes = R.string.alt_key_editor_clone_profile_description,
        route = SettingRoute(SettingsDestination.DeviceSymLayerEditor)),
    SettingEntry("hardware.alt_editor.import", R.string.alt_key_editor_import_title,
        summaryRes = R.string.alt_key_editor_transfer_description,
        route = SettingRoute(SettingsDestination.DeviceSymLayerEditor)),
    SettingEntry(SettingLinkIds.PRIVACY_CLEAN_LINKS, R.string.clean_links_title,
        summaryRes = R.string.clean_links_description,
        route = SettingRoute(SettingsDestination.Advanced)),
    SettingEntry(SettingLinkIds.PRIVACY_PASTE_SUGGESTION, R.string.paste_suggestion_title,
        summaryRes = R.string.paste_suggestion_description,
        route = SettingRoute(SettingsDestination.Advanced))
)
